name: Update Palette System Data

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 1 * *" # monthly

jobs:
  update-palette-system-data:
    name: Update Palette System Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run update script
        run: npm run update-palette-system-data

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'chore: Update Palette System Data'
          commit-message: update palette system data
          branch: automatic-palette-system-update
          body: |
            Updates the palette system data for Tumblr's native palettes.
